vich_uploader:
    db_driver: orm

    mappings:
        logoBrand:
            uri_prefix: '%logoBrand%'
            upload_destination: '%kernel.project_dir%/public%logoBrand%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true